# Generated by Django 3.2.3 on 2021-12-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='share_value',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
