# Generated by Django 3.2.3 on 2021-12-20 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_company_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ownership_company', to='base.company'),
            preserve_default=False,
        ),
    ]
