# Generated by Django 3.2.3 on 2021-12-20 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_ownership_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='signatory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signing_person', to='base.person'),
        ),
    ]
