# Generated by Django 3.1.7 on 2022-01-04 10:20

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220103_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='moa_signing',
            field=thumbnails.fields.ImageField(blank=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='company',
            name='office_signing',
            field=thumbnails.fields.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
