# Generated by Django 3.1.7 on 2022-01-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220104_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
