# Generated by Django 4.0.3 on 2022-04-01 12:14

from django.db import migrations, models
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20220105_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('nationality', models.CharField(blank=True, max_length=250)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('data', models.CharField(blank=True, max_length=10000)),
                ('face', thumbnails.fields.ImageField(blank=True, upload_to='static/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='signatory',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Ownership',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
