# Generated by Django 4.0.3 on 2022-04-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_profile_remove_organization_signatory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='it2',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
