# Generated by Django 4.0.3 on 2022-04-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_profile_it2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='face_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
