# Generated by Django 4.0.3 on 2022-04-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_profile_it2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='it2',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
