# Generated by Django 4.0.3 on 2022-04-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_profile_it2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doc_id',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
