# Generated by Django 4.0.3 on 2022-04-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_profile_doc_id_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verify',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
